#!/usr/bin/env python3
import argparse, json, html
from pathlib import Path

PALETTES={
'cinematic':('#07090f','#121725','#f5f7ff','#7dd3fc','#c4b5fd'),
'urban-neon':('#070811','#121426','#f8f8ff','#67e8f9','#f0abfc'),
'nature':('#0a1712','#14261d','#f3f7f2','#86efac','#fde68a'),
'island':('#06202a','#0b3542','#f4fdff','#67e8f9','#fcd34d'),
'japan-minimal':('#f4f1ea','#ffffff','#171717','#9f1239','#57534e')}

def load(path): return json.loads(Path(path).read_text(encoding='utf-8'))
def js_json(data): return json.dumps(data,ensure_ascii=False,separators=(',',':')).replace('</script>','<\\/script>')

def build(data):
    meta=data.get('meta') or {}; trip=data.get('trip') or {}; theme=meta.get('theme','cinematic')
    if theme not in PALETTES: theme='cinematic'
    bg,surface,text,accent,accent2=PALETTES[theme]
    title=html.escape(trip.get('title','Travel Copilot'))
    subtitle=html.escape(trip.get('subtitle',''))
    hero=trip.get('heroImage') or ''
    hero_css=f"url('{hero.replace(chr(39),'%27')}')" if isinstance(hero,str) and hero.startswith(('https://','http://')) else 'none'
    embedded=js_json(data)
    return f'''<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="{bg}"><title>{title}</title>
<style>
:root{{--bg:{bg};--surface:{surface};--text:{text};--accent:{accent};--accent2:{accent2};--muted:color-mix(in srgb,var(--text) 62%,transparent);--line:color-mix(in srgb,var(--text) 14%,transparent);--shadow:0 22px 70px rgba(0,0,0,.24);--radius:24px}}
*{{box-sizing:border-box}}html{{scroll-behavior:smooth}}body{{margin:0;background:var(--bg);color:var(--text);font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Hiragino Sans GB",sans-serif;overflow-x:hidden}}
button,select{{font:inherit}}button{{cursor:pointer}}a{{color:inherit}}.wrap{{width:min(1120px,100%);margin:auto;padding:0 18px 110px}}
.hero{{min-height:66svh;position:relative;display:flex;align-items:flex-end;overflow:hidden;background-image:linear-gradient(180deg,rgba(4,6,12,.18),var(--bg) 94%),{hero_css};background-size:cover;background-position:center}}
.hero:before,.hero:after{{content:"";position:absolute;border-radius:50%;filter:blur(70px);opacity:.28;animation:float 12s ease-in-out infinite alternate;pointer-events:none}}.hero:before{{width:42vw;height:42vw;left:-10vw;top:4vh;background:var(--accent)}}.hero:after{{width:32vw;height:32vw;right:-8vw;top:22vh;background:var(--accent2);animation-delay:-4s}}
.hero-inner{{position:relative;z-index:2;width:min(1120px,100%);margin:auto;padding:70px 18px 54px}}.eyebrow{{letter-spacing:.18em;text-transform:uppercase;font-size:12px;opacity:.72}}h1{{font-size:clamp(42px,10vw,94px);line-height:.94;margin:10px 0 16px;max-width:850px;letter-spacing:-.045em}}.subtitle{{font-size:clamp(16px,3.5vw,23px);opacity:.78;max-width:720px}}
.hero-meta{{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}}.pill{{border:1px solid var(--line);background:color-mix(in srgb,var(--surface) 78%,transparent);backdrop-filter:blur(14px);padding:9px 13px;border-radius:999px;font-size:13px}}
.section{{margin-top:26px}}.glass{{background:color-mix(in srgb,var(--surface) 88%,transparent);border:1px solid var(--line);border-radius:var(--radius);box-shadow:var(--shadow);backdrop-filter:blur(18px)}}
.now-card{{padding:20px;display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center;position:sticky;top:10px;z-index:20}}.now-kicker{{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--accent)}}.now-title{{font-size:24px;font-weight:760;margin:5px 0}}.muted{{color:var(--muted)}}.pulse{{width:11px;height:11px;border-radius:50%;background:var(--accent);box-shadow:0 0 0 0 color-mix(in srgb,var(--accent) 45%,transparent);animation:pulse 2s infinite}}
.day-tabs{{display:flex;gap:10px;overflow:auto;padding:5px 1px 8px;scroll-snap-type:x mandatory;scrollbar-width:none}}.day-tabs::-webkit-scrollbar{{display:none}}.day-btn{{min-width:126px;scroll-snap-align:start;border:1px solid var(--line);background:transparent;color:var(--text);border-radius:18px;padding:13px 14px;text-align:left;transition:.25s transform,.25s background}}.day-btn.active{{background:var(--text);color:var(--bg);transform:translateY(-2px)}}.day-btn small{{display:block;opacity:.64;margin-top:4px}}
.day-head{{display:flex;justify-content:space-between;gap:14px;align-items:end;margin:28px 0 14px}}.day-head h2{{font-size:30px;margin:0}}.day-grid{{display:grid;grid-template-columns:minmax(0,1.12fr) minmax(300px,.88fr);gap:18px;align-items:start}}
.timeline{{position:relative;padding:10px 0 10px 24px}}.timeline:before{{content:"";position:absolute;left:6px;top:8px;bottom:8px;width:2px;background:linear-gradient(var(--accent),var(--line))}}.event-card{{position:relative;padding:18px;margin:0 0 13px;transition:.28s transform,.28s border-color,.28s background;content-visibility:auto}}.event-card:before{{content:"";position:absolute;width:12px;height:12px;border-radius:50%;left:-25px;top:25px;background:var(--bg);border:3px solid var(--accent)}}.event-card.active{{transform:translateX(5px);border-color:color-mix(in srgb,var(--accent) 55%,transparent);background:color-mix(in srgb,var(--surface) 92%,var(--accent) 8%)}}
.event-top{{display:flex;gap:12px;justify-content:space-between;align-items:flex-start}}.event-time{{font-variant-numeric:tabular-nums;color:var(--accent);font-weight:700;font-size:13px}}.event-title{{font-size:20px;font-weight:760;margin:4px 0}}.event-desc{{line-height:1.6;color:var(--muted)}}.event-actions{{display:flex;flex-wrap:wrap;gap:8px;margin-top:13px}}.action{{border:1px solid var(--line);background:transparent;color:var(--text);border-radius:999px;padding:9px 12px;text-decoration:none;font-size:13px}}.action.primary{{background:var(--text);color:var(--bg);border-color:transparent}}.done{{opacity:.55}}.done .event-title{{text-decoration:line-through}}
.priority{{font-size:11px;border:1px solid var(--line);border-radius:999px;padding:5px 8px}}.priority.P0{{color:#fb7185}}.priority.P1{{color:#fbbf24}}
.map-shell{{position:sticky;top:92px;overflow:hidden;min-height:500px}}#map{{height:500px;background:linear-gradient(135deg,var(--surface),var(--bg))}}.map-fallback{{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:24px;text-align:center;color:var(--muted);pointer-events:none}}.map-online .map-fallback{{display:none}}
.overview-grid{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}.mini-section{{padding:20px;margin-top:16px}}.overview-grid .mini-section{{margin-top:0}}.mini-section h3{{margin:0 0 14px;font-size:20px}}.booking-row{{padding:11px 0;border-top:1px solid var(--line)}}.booking-row:first-child{{border-top:0}}.booking-title{{font-weight:750}}.budget-total{{font-size:26px;font-weight:800;letter-spacing:-.02em;margin:2px 0 12px}}.budget-row{{display:flex;justify-content:space-between;gap:16px;padding:8px 0;border-top:1px solid var(--line);font-size:13px}}.check-row{{display:flex;gap:11px;align-items:flex-start;padding:10px 0;border-top:1px solid var(--line)}}.check-row:first-of-type{{border-top:0}}input[type=checkbox]{{width:20px;height:20px;accent-color:var(--accent)}}
.bottom-nav{{position:fixed;z-index:50;left:50%;bottom:max(12px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:7px;padding:7px;background:color-mix(in srgb,var(--surface) 90%,transparent);border:1px solid var(--line);backdrop-filter:blur(18px);border-radius:999px;box-shadow:var(--shadow)}}.bottom-nav button{{border:0;background:transparent;color:var(--text);padding:10px 13px;border-radius:999px}}.bottom-nav button.primary{{background:var(--text);color:var(--bg)}}
.modal{{position:fixed;inset:0;z-index:80;background:rgba(0,0,0,.56);display:none;align-items:flex-end;justify-content:center;padding:16px}}.modal.open{{display:flex}}.sheet{{width:min(620px,100%);max-height:88svh;overflow:auto;background:var(--surface);border:1px solid var(--line);border-radius:28px;padding:22px;box-shadow:var(--shadow)}}.sheet h2{{margin-top:0}}.field{{margin:16px 0}}.field label{{display:block;margin-bottom:8px;font-size:13px;color:var(--muted)}}select{{width:100%;background:var(--bg);color:var(--text);border:1px solid var(--line);border-radius:14px;padding:12px}}.toggle-row{{display:flex;gap:10px;align-items:center;margin:11px 0}}.wide{{width:100%;border:0;border-radius:14px;padding:13px;background:var(--text);color:var(--bg);font-weight:750}}
.reveal{{opacity:0;transform:translateY(18px);transition:.65s opacity,.65s transform}}.reveal.in{{opacity:1;transform:none}}.footer{{margin:30px 0;color:var(--muted);font-size:12px;line-height:1.7}}
@keyframes float{{to{{transform:translate3d(4vw,2vh,0) scale(1.08)}}}}@keyframes pulse{{70%{{box-shadow:0 0 0 12px transparent}}100%{{box-shadow:0 0 0 0 transparent}}}}
@media(max-width:820px){{.hero{{min-height:58svh}}.overview-grid,.day-grid{{grid-template-columns:1fr}}.map-shell{{position:relative;top:auto;min-height:360px}}#map{{height:360px}}.now-card{{top:7px}}}}
@media(prefers-reduced-motion:reduce){{*,*:before,*:after{{animation:none!important;transition:none!important;scroll-behavior:auto!important}}.reveal{{opacity:1;transform:none}}}}
</style>
<link rel="preconnect" href="https://unpkg.com" crossorigin>
</head><body>
<header class="hero"><div class="hero-inner"><div class="eyebrow">Travel Copilot · v{html.escape(str(meta.get('version','1.0')))}</div><h1>{title}</h1><div class="subtitle">{subtitle or html.escape(trip.get('summary',''))}</div><div class="hero-meta"><span class="pill">{html.escape(trip.get('startDate',''))} → {html.escape(trip.get('endDate',''))}</span><span class="pill">{html.escape(trip.get('timezone',''))}</span><span class="pill" id="travelerPill">同行模式</span></div></div></header>
<main class="wrap">
<section class="section glass now-card" id="nowCard"><div><div class="now-kicker">NOW / NEXT</div><div class="now-title" id="nowTitle">正在读取你的行程时间…</div><div class="muted" id="nowDetail"></div></div><div class="pulse"></div></section>
<section class="section"><div class="day-tabs" id="dayTabs"></div></section>
<section class="section overview-grid"><div class="glass mini-section reveal"><h3>关键预订 / 固定项</h3><div id="bookingOverview"></div></div><div class="glass mini-section reveal"><h3>预算快照</h3><div id="budgetOverview"></div></div></section>
<section class="section" id="daySection"><div class="day-head"><div><div class="eyebrow" id="dayDate"></div><h2 id="dayTitle"></h2></div><div class="muted" id="dayArea"></div></div><div class="day-grid"><div><div class="timeline" id="timeline"></div><div class="glass mini-section reveal"><h3>今日提示</h3><div id="dayTips" class="muted"></div></div></div><div><div class="glass map-shell reveal"><div id="map"></div><div class="map-fallback">地图需要联网加载；行程、地址和导航按钮仍可使用。</div></div><div class="glass mini-section reveal"><h3>我的准备清单</h3><div id="checklist"></div></div></div></div></section>
<section class="section glass mini-section reveal" id="planBSection"><h3>Plan B</h3><div id="planB" class="muted"></div></section>
<div class="footer">{html.escape(data.get('disclaimer','行程信息可能变化，出发前请以官方渠道为准。'))}<br>本页面的完成状态仅保存在当前设备。日历提醒为导入快照；行程更新后请重新导出。</div>
</main>
<nav class="bottom-nav"><button onclick="scrollToTop()">今天</button><button onclick="openReminder()">🔔 提醒</button><button class="primary" onclick="jumpNext()">下一站</button></nav>
<div class="modal" id="reminderModal" onclick="if(event.target===this)closeReminder()"><div class="sheet"><h2>安装我的旅行提醒</h2><p class="muted">静态 HTML 不会在关闭后可靠后台运行。这里生成属于你的 ICS，导入手机日历后由系统提醒。</p><div class="field"><label>我是</label><select id="travelerSelect"></select></div><div class="field"><label>提醒等级</label><div class="toggle-row"><input id="p0" type="checkbox" checked><span>P0 · 绝不能错过</span></div><div class="toggle-row"><input id="p1" type="checkbox" checked><span>P1 · 重要安排</span></div><div class="toggle-row"><input id="p2" type="checkbox"><span>P2 · 普通行程</span></div></div><button class="wide" onclick="downloadICS()">生成并下载我的 ICS</button><button class="wide" style="margin-top:8px;background:transparent;color:var(--text);border:1px solid var(--line)" onclick="closeReminder()">关闭</button></div></div>
<script id="trip-data" type="application/json">{embedded}</script>
<script>
const DATA=JSON.parse(document.getElementById('trip-data').textContent);const TRIP=DATA.trip||{{}},DAYS=DATA.days||[],META=DATA.meta||{{}};
const stateKey='travel-copilot:'+String(TRIP.title||'trip');let state={{done:{{}},checks:{{}},traveler:''}};try{{state=Object.assign(state,JSON.parse(localStorage.getItem(stateKey)||'{{}}'))}}catch(e){{}};
function saveState(){{localStorage.setItem(stateKey,JSON.stringify(state))}}function esc(s){{return String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]))}}
function dateInTZ(){{try{{const p=new Intl.DateTimeFormat('en-CA',{{timeZone:TRIP.timezone,year:'numeric',month:'2-digit',day:'2-digit'}}).formatToParts(new Date());let o={{}};p.forEach(x=>o[x.type]=x.value);return `${{o.year}}-${{o.month}}-${{o.day}}`}}catch(e){{return new Date().toISOString().slice(0,10)}}}}
function timeInTZ(){{try{{return new Intl.DateTimeFormat('en-GB',{{timeZone:TRIP.timezone,hour:'2-digit',minute:'2-digit',hour12:false}}).format(new Date())}}catch(e){{return new Date().toTimeString().slice(0,5)}}}}
let activeDay=Math.max(0,DAYS.findIndex(d=>d.date===dateInTZ()));if(activeDay<0)activeDay=0;let map=null,mapMarkers={{}},routeLine=null;
function money(v){{try{{return new Intl.NumberFormat('zh-CN').format(Number(v||0))}}catch(e){{return String(v||0)}}}}
function renderOverview(){{const b=document.getElementById('bookingOverview'),items=DATA.bookings||[];b.innerHTML=items.length?items.map(x=>`<div class="booking-row"><div class="booking-title">${{esc(x.title||x.type||'预订')}}</div>${{x.reference?`<div class="muted" style="font-size:12px;margin-top:4px">${{esc(x.reference)}}</div>`:''}}</div>`).join(''):'<div class="muted">尚未写入固定预订。</div>';const box=document.getElementById('budgetOverview'),bd=DATA.budget||{{}},rows=bd.perPerson||[];if(!rows.length){{box.innerHTML='<div class="muted">尚未录入预算。</div>';return}}let cur=bd.currency==='CNY'?'¥':(bd.currency||'');box.innerHTML=`<div class="budget-total">${{cur}}${{money(bd.totalMin)}} — ${{cur}}${{money(bd.totalMax)}} / 人</div>`+rows.map(r=>`<div class="budget-row"><span>${{esc(r.category)}}</span><span>${{cur}}${{money(r.min)}}–${{cur}}${{money(r.max)}}</span></div>`).join('')+`${{bd.note?`<div class="muted" style="font-size:12px;margin-top:10px">${{esc(bd.note)}}</div>`:''}}`}}
function renderTabs(){{const el=document.getElementById('dayTabs');el.innerHTML='';DAYS.forEach((d,i)=>{{const b=document.createElement('button');b.className='day-btn'+(i===activeDay?' active':'');b.innerHTML=`DAY ${{i+1}}<small>${{esc(d.date)}} · ${{esc(d.title||'')}}</small>`;b.onclick=()=>{{activeDay=i;renderDay();renderTabs();}};el.appendChild(b)}})}}
function navLinks(e){{const l=e.location||{{}};if(typeof l.lat!=='number'||typeof l.lng!=='number')return '';const q=encodeURIComponent(l.name||e.title||'Destination'),lat=l.lat,lng=l.lng;const ios=/iPhone|iPad|iPod/.test(navigator.userAgent);let primary=ios?`https://maps.apple.com/?ll=${{lat}},${{lng}}&q=${{q}}`:`https://www.google.com/maps/search/?api=1&query=${{lat}},${{lng}}`;let amap=`https://uri.amap.com/marker?position=${{lng}},${{lat}}&name=${{q}}&coordinate=wgs84&callnative=1&src=travel-copilot`;return `<a class="action primary" target="_blank" rel="noopener" href="${{primary}}">导航</a><a class="action" target="_blank" rel="noopener" href="${{amap}}">高德</a>`}}
function relevant(x){{const a=x.assignedTo||[];return !state.traveler||!a.length||a.includes(state.traveler)}}
function eventHTML(e){{const done=!!state.done[e.id],p=e.priority||'P2',loc=e.location||{{}};return `<article class="glass event-card reveal ${{done?'done':''}}" data-id="${{esc(e.id)}}"><div class="event-top"><div><div class="event-time">${{esc(e.start||'')}}${{e.end?' — '+esc(e.end):''}}</div><div class="event-title">${{esc(e.title)}}</div></div><span class="priority ${{p}}">${{p}}</span></div>${{e.description?`<div class="event-desc">${{esc(e.description)}}</div>`:''}}${{loc.address?`<div class="muted" style="margin-top:9px;font-size:13px">📍 ${{esc(loc.address)}}</div>`:''}}<div class="event-actions">${{navLinks(e)}}<button class="action" onclick="toggleDone('${{String(e.id).replace(/'/g,"\\'")}}')">${{done?'恢复':'✓ 完成'}}</button></div></article>`}}
function renderDay(){{const d=DAYS[activeDay]||{{events:[]}};document.getElementById('dayDate').textContent=d.date||'';document.getElementById('dayTitle').textContent=d.title||`Day ${{activeDay+1}}`;document.getElementById('dayArea').textContent=d.area||'';document.getElementById('timeline').innerHTML=(d.events||[]).map(eventHTML).join('')||'<div class="muted">这一天还没有事件。</div>';document.getElementById('dayTips').innerHTML=(d.tips||[]).map(x=>`<div style="margin:7px 0">• ${{esc(x)}}</div>`).join('')||'暂无特别提示';renderChecklist();renderPlanB();observeReveals();observeEvents();refreshMap();renderNow()}}
function toggleDone(id){{state.done[id]=!state.done[id];saveState();renderDay()}}
function renderChecklist(){{const box=document.getElementById('checklist');const arr=(DATA.checklists||[]).filter(relevant);box.innerHTML=arr.map(x=>`<label class="check-row"><input type="checkbox" ${{state.checks[x.id]?'checked':''}} onchange="state.checks['${{String(x.id).replace(/'/g,"\\'")}}']=this.checked;saveState()"><span><b>${{esc(x.title)}}</b>${{x.due?`<div class="muted" style="font-size:12px">建议 ${{esc(x.due)}} 前完成</div>`:''}}</span></label>`).join('')||'<div class="muted">没有分配给你的准备事项。</div>'}}
function renderPlanB(){{const arr=(DATA.planB||[]).filter(x=>!x.forDate||x.forDate===(DAYS[activeDay]||{{}}).date);document.getElementById('planBSection').style.display=(DATA.planB||[]).length?'block':'none';document.getElementById('planB').innerHTML=arr.length?arr.map(x=>`<div style="margin:8px 0">• ${{esc(x.trigger||'备选')}}${{x.forDate?' · '+esc(x.forDate):''}}</div>`).join(''):'本日暂无特定备选方案。'}}
function minutes(t){{if(!t)return null;let [h,m]=t.split(':').map(Number);return h*60+m}}function renderNow(){{const today=dateInTZ(),now=minutes(timeInTZ()),d=DAYS.find(x=>x.date===today);let title='当前不在行程日期内',detail=`旅行：${{TRIP.startDate||''}} → ${{TRIP.endDate||''}}`;if(d){{let ev=(d.events||[]);let cur=ev.find(e=>minutes(e.start)<=now&&minutes(e.end||e.start)>=now),next=ev.find(e=>minutes(e.start)>now&&!state.done[e.id]);if(cur){{title=cur.title;detail=`现在 · ${{cur.start||''}}${{cur.end?'–'+cur.end:''}}${{next?' · 下一站 '+next.title:''}}`}}else if(next){{title='下一站 · '+next.title;detail=`建议关注 ${{next.start||''}} 的安排`}}else{{title='今天的主要行程已结束';detail='可以整理照片、票据和明日准备。'}}}}document.getElementById('nowTitle').textContent=title;document.getElementById('nowDetail').textContent=detail}}
function jumpNext(){{const cards=[...document.querySelectorAll('.event-card')];const next=cards.find(c=>!state.done[c.dataset.id]);if(next)next.scrollIntoView({{behavior:'smooth',block:'center'}});else window.scrollTo({{top:0,behavior:'smooth'}})}}function scrollToTop(){{window.scrollTo({{top:0,behavior:'smooth'}})}}
function observeReveals(){{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('in')),{{threshold:.08}});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}}
function observeEvents(){{const io=new IntersectionObserver(es=>es.forEach(en=>{{if(en.isIntersecting){{document.querySelectorAll('.event-card').forEach(c=>c.classList.remove('active'));en.target.classList.add('active');focusMap(en.target.dataset.id)}}}}),{{rootMargin:'-35% 0px -50% 0px',threshold:0}});document.querySelectorAll('.event-card').forEach(x=>io.observe(x))}}
function loadLeaflet(){{if(window.L)return Promise.resolve();return new Promise((resolve,reject)=>{{let css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);let s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)}})}}
async function refreshMap(){{const pts=(DAYS[activeDay]?.events||[]).filter(e=>typeof e.location?.lat==='number'&&typeof e.location?.lng==='number');if(!pts.length)return;try{{await loadLeaflet();if(!map){{map=L.map('map',{{zoomControl:true,attributionControl:true}});L.tileLayer('https://{{s}}.tile.openstreetmap.org/{{z}}/{{x}}/{{y}}.png',{{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>'}}).addTo(map)}}Object.values(mapMarkers).forEach(m=>m.remove());mapMarkers={{}};if(routeLine)routeLine.remove();pts.forEach((e,i)=>{{let m=L.marker([e.location.lat,e.location.lng]).addTo(map).bindPopup(`<b>${{esc(e.title)}}</b><br>${{esc(e.start||'')}}`);mapMarkers[e.id]=m}});let coords=pts.map(e=>[e.location.lat,e.location.lng]);routeLine=L.polyline(coords,{{weight:4,opacity:.75,dashArray:'10 10'}}).addTo(map);map.fitBounds(routeLine.getBounds(),{{padding:[25,25]}});document.querySelector('.map-shell').classList.add('map-online')}}catch(e){{console.warn('Map unavailable',e)}}}}
function focusMap(id){{let m=mapMarkers[id];if(map&&m){{map.panTo(m.getLatLng(),{{animate:true,duration:.7}});m.openPopup()}}}}
function openReminder(){{document.getElementById('reminderModal').classList.add('open')}}function closeReminder(){{document.getElementById('reminderModal').classList.remove('open')}}
function setupTravelers(){{let s=document.getElementById('travelerSelect');let arr=DATA.travelers||[];s.innerHTML='<option value="">所有同行者 / 通用</option>'+arr.map(t=>`<option value="${{esc(t.id)}}">${{esc(t.name)}}</option>`).join('');s.value=state.traveler||'';s.onchange=()=>{{state.traveler=s.value;saveState();syncTraveler();renderChecklist()}};syncTraveler()}}function syncTraveler(){{let t=(DATA.travelers||[]).find(x=>x.id===state.traveler);document.getElementById('travelerPill').textContent=t?'我是 '+t.name:'同行模式'}}
function icsEsc(s){{const bs=String.fromCharCode(92);return String(s||'').replaceAll(bs,bs+bs).replaceAll(String.fromCharCode(10),bs+'n').replaceAll(',',bs+',').replaceAll(';',bs+';')}}function utcStamp(iso){{let d=new Date(iso);if(isNaN(d))return null;return d.toISOString().replace(/[-:]/g,'').replace(/[.][0-9]{{3}}Z$/,'Z')}}function localStamp(day,time){{return day.replace(/-/g,'')+'T'+time.replace(':','')+'00'}}
function prioritySelected(p){{return document.getElementById(String(p).toLowerCase()).checked}}function alarms(p){{return p==='P0'?[120,30,10]:p==='P1'?[60,20]:[15]}}
function downloadICS(){{let traveler=document.getElementById('travelerSelect').value;let rel=x=>{{let a=x.assignedTo||[];return !traveler||!a.length||a.includes(traveler)}};let entries=[];(DATA.reminders||[]).forEach(r=>{{let p=r.priority||'P1';if(rel(r)&&prioritySelected(p)&&r.datetime)entries.push({{id:r.id,title:r.title,description:r.description||'',iso:r.datetime,alarm:r.alarmMinutes||alarms(p)}})}});let related=new Set((DATA.reminders||[]).map(r=>r.relatedEventId).filter(Boolean));DAYS.forEach(d=>(d.events||[]).forEach(e=>{{let p=e.priority||'P2';if(!e.start||related.has(e.id)||!rel(e)||!prioritySelected(p))return;entries.push({{id:e.id,title:e.title,description:e.description||'',day:d.date,time:e.start,alarm:alarms(p)}})}}));let now=new Date().toISOString().replace(/[-:]/g,'').replace(/[.][0-9]{{3}}Z$/,'Z');let lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Travel Copilot//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH',`X-WR-CALNAME:${{icsEsc(TRIP.title)}} reminders v${{icsEsc(META.version||'1.0')}}`];entries.forEach(x=>{{lines.push('BEGIN:VEVENT',`UID:${{icsEsc(x.id)}}@travel-copilot`,`DTSTAMP:${{now}}`,`SUMMARY:${{icsEsc(x.title)}}`);if(x.iso){{let u=utcStamp(x.iso);if(u)lines.push('DTSTART:'+u)}}else lines.push(`DTSTART;TZID=${{TRIP.timezone||'UTC'}}:${{localStamp(x.day,x.time)}}`);if(x.description)lines.push('DESCRIPTION:'+icsEsc(x.description));(x.alarm||[]).forEach(m=>lines.push('BEGIN:VALARM',`TRIGGER:-PT${{m}}M`,'ACTION:DISPLAY',`DESCRIPTION:${{icsEsc(x.title)}}`,'END:VALARM'));lines.push('END:VEVENT')}});lines.push('END:VCALENDAR');let nl=String.fromCharCode(13,10);let blob=new Blob([lines.join(nl)+nl],{{type:'text/calendar;charset=utf-8'}}),url=URL.createObjectURL(blob),a=document.createElement('a');let who=(DATA.travelers||[]).find(x=>x.id===traveler)?.name||'group';a.href=url;a.download=`${{TRIP.title||'trip'}}-${{who}}-reminders-v${{META.version||'1.0'}}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
renderOverview();renderTabs();renderDay();setupTravelers();setInterval(renderNow,60000);
</script></body></html>'''

def main():
    ap=argparse.ArgumentParser();ap.add_argument('json_file');ap.add_argument('-o','--output',default='trip.html');a=ap.parse_args();data=load(a.json_file);Path(a.output).write_text(build(data),encoding='utf-8');print(a.output)
if __name__=='__main__': main()
